### ISSUE TITLE
Weird touchpad behavior

### ISSUE THREAD

**Issue by kuchibhr7** [NeoBlizzard-verbose/Dell_Inspiron_13-7378-Hackintosh#3]
First things first, touchpad is PS/2 and not I2C. Only the touchscreen is and works fine with VoodooI2C.

Using VoodooPS2Controller, touchpad works but lacks momentum. Can be fixed by increasing touchpad speed.
The buttons make no sense. This is not a Clickpad. Every click is a long press. Fixed by disabling force touch in settings.
Both the keys act as left click, now. Fixed by remapping bottom right button to secondary click in settings.

The loss? two-finger tap does not work as secondary click anymore.

*sighs

**Comment by kuchibhr7** [comment]
This is indeed a clickpad, as the entire surface is clickable.
Apologies for the confusion, had to replace thermal paste and noticed that the battery has swelled. Removing it makes my clickpad feel better, will update OS X behavior soon...

**Comment by pixotna** [comment]
Hi, is the touch screen working properly? I downloaded your config file, but voodooi2l is not used in it. I would like to know how you drive the touch screen.

I added voodooi2c and voodooi2chid to my configuration file and I can use the touch screen properly, but the touchpad doesn't work. If voodooi2c is not added, the touchpad works normally but the touch screen does not work.

**Comment by kuchibhr7** [comment]
> Hi, is the touch screen working properly? I downloaded your config file, but voodooi2l is not used in it. I would like to know how you drive the touch screen.

Yes, it works using voodooi2c. I haven't got the time to update the BSP which is why it's missing.  

> I added voodooi2c and voodooi2chid to my configuration file and I can use the touch screen properly, but the touchpad doesn't work. If voodooi2c is not added, the touchpad works normally but the touch screen does not work.

agreed, making the touchscreen and touchpad work seems like a difficult task to do. have you tried driving the touchpad using voodoosmbus? that worked for me but the behavior was pretty weird...

**Comment by pixotna** [comment]
> > Hi, is the touch screen working properly? I downloaded your config file, but voodooi2l is not used in it. I would like to know how you drive the touch screen.
> 
> Yes, it works using voodooi2c. I haven't got the time to update the BSP which is why it's missing.
> 
> > I added voodooi2c and voodooi2chid to my configuration file and I can use the touch screen properly, but the touchpad doesn't work. If voodooi2c is not added, the touchpad works normally but the touch screen does not work.
> 
> agreed, making the touchscreen and touchpad work seems like a difficult task to do. have you tried driving the touchpad using voodoosmbus? that worked for me but the behavior was pretty weird...

I've fixed the issue and now both the touchscreen and touchpad work fine at the same time. I modified the Info.plist in VoodooI2CHID.kext, deleted 《key》VoodooI2CHIDDevice《/key》 and the following 《dict》《/dict》. Problem solved.

**Comment by pixotna** [comment]
The key value in VoodooI2CHID conflicts with VoodooPS2Trackpad

**Comment by kuchibhr7** [comment]
Splendid! If possible, could you please make a PR with the changes you
mentioned? I'll review it and merge, so that this issue can be marked as
resolved =)

**Comment by pixotna** [comment]
> Splendid! If possible, could you please make a PR with the changes you mentioned? I'll review it and merge, so that this issue can be marked as resolved =)
[https://github.com/pixotna/Dell-7378-Hackintosh](url)

**Comment by kuchibhr7** [comment]
Back to working on this again, after a break.
I added your kext, updated OC and did some clean-up. It boots again :D
However, the touchscreen does not work in the Recovery Environment. Is this normal behavior?

**Comment by kuchibhr7** [comment]
I clearly lost touch (pun intended) with hackintoshes :/

Touch doesn't work for me. Logs say invalid parameter with your modified kext.
On top of that, I don't think I can work on this actively, anymore...

**Comment by pixotna** [comment]
My touchscreen works fine under BigSur and Monterey

**Comment by kuchibhr7** [comment]
Share your EFI, if it's okay for you. I'll push it as a release and add you
as a contributor;)

**Comment by pixotna** [comment]
> deleted 《key》VoodooI2CHIDDevice《/key》 and the following 《dict》《/dict》

https://github.com/pixotna/Dell-inspiron7368-Hackintosh

**Comment by kuchibhr7** [comment]
huh. Looks like yours is a 7368. Not sure how it affects functionality. Could it be that this is the reason why you have touch working and I don't?

**Comment by pixotna** [comment]
The theoretical difference between 7368 and 7378 is only in the CPU, but the touch screen may use products from different suppliers.

在 2023年11月26日，17:26，Rishi Kuchibhotla ***@***.***> 写道：

﻿

huh. Looks like yours is a 7368. Not sure how it affects functionality. Could it be that this is the reason why you have touch working and I don't?

**Comment by kuchibhr7** [comment]
I messed up the order of kexts loading. Referred to your efi and made changes. Touchscreen and touchpad work flawlessly, now :D

It's safe to close this issue now. Thanks for your contribution :)
