### ISSUE TITLE
Cant boot USB

### ISSUE THREAD

**Issue by Myla22221** [NeoBlizzard-verbose/Dell_Inspiron_13-7378-Hackintosh#4]
When booting the USB with this EFI using Macos Monterey, I get the error “Selected boot device failed. Press any key to reboot the system”. Also the usb shows up in the Legacy boot section in the F12 boot menu. I tried different USB’s using rufus and belena Etcher and even making the USB on a native mac. After that I use a terminal command to allow me to see the EFI section of the usb then put this efi there. Hopefully that is enough info for help. Thanks

**Comment by kuchibhr7** [comment]
Have you tried making the bootable USB using Dortania's guide? It always worked for me that way. Let me look into it and get back to you soon :)

Edit:- or, it could be that the config plist has a bad MinVersion of macOS?
Edit2:- the min version is catalina, Monterey should work fine...

**Comment by kuchibhr7** [comment]
Monterey booted just fine for me. Both on the release EFI and latest Opencore. Make sure that you didn't mess up the setup. Also use the release EFI, don't download the code as zip.

**Comment by Myla22221** [comment]
Oops, I accidentally closed it and re-opened but I have used the release efi, using the dortania guide just having to flash the usb with Monterey, mounting the efi portion of the usb and switching it with this one. I noticed that I have the i7 version of the laptop which might be causing the issue? Thanks again

**Comment by Myla22221** [comment]
Im so clumsy, its been a minute since ive used github 🤪
